rake task for dumping, restoring and anonymizing user data
roschaefer/rundfunk-mitbestimmen pull request #1013
Opened 2019-01-05 14:42 UTC by dkuku

Created rake task for anonymizing user data.

#### Description

Also for dumping and restoring development database
Currently to use it you need to dump your data `rake db:dump` and backup the file `db/backend.dump`
Then you can run `rake db:anonymize_user` which changes current user table
Now you can run `rake db:dump` again to dump anonymized data
to restore the original file move it to `db/` and run `rake db/restore`
Waiting for suggestions to extend this.

#### Motivation and Context

To be in compliace with current European law we can't get developers access to user data - this rake task annonymizes the user table 

#### How Has This Been Tested?

Tested locally on seeded data - might need some adjustments, I annonymized only the data I currently have access to

#### alternative solution using shell and temporary database
http://www.michaelkrenz.de/2012/08/05/how-to-anonymize-data-in-a-postgresql-database/

## dump data
`pg_dump database > original_datadump`

## create temp database
`createdb tempDB`

## import data to temp
`psql tempDB < ./original_datadump`

## run anonymize script - on the botttom
`psql tempDB < ./anonymize_db.sql`

## dump anonymized data
`pg_dump tempDB > anon_dump.sql`

## delete temporary table
`dropdb tempDB`

```sql
/*delete field content
    update users set encrypted_password = NULL;
    */
    update users set encrypted_password = 'asdf';

/*anonymize emails, lat and lng*/
    update users set email = 'user' || id || '@rundfunk.com';
    update users set latitude = 51 + 0.001 * id;
    update users set longitude = 22 - 0.001 * id;

/*anonymize other data*/
    update city set
    city = translate(message, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZC', 'aaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAA');

```

2019-01-09 16:43 UTC, roschaefer requested changes
@dkuku looks good! Just the usual nitpickings. I'm gonna try it out on my machine now and send you a an anonymized dump.

One question: Don't you think that keeping the ids will allow for de-anonymization? Maybe we should shuffle the user ids?

2019-01-09 16:43 UTC, roschaefer commented on backend/lib/tasks/db.rake
> +      User.all.each do |user|
```suggestion
      User.find_each do |user|
```

2019-01-09 16:43 UTC, roschaefer commented on backend/lib/tasks/db.rake
> +        user.email = "user#{user.id}@rundfunk.com"
```suggestion
        user.email = "user#{user.id}@example.org"
```
The domain `rundfunk.com` exists. The domain http://example.org/ is intended to be used for such purposes.

2019-01-09 16:43 UTC, roschaefer commented on backend/lib/tasks/db.rake
> +      end
@dkuku you can probably update all the users in one sql statement: https://apidock.com/rails/ActiveRecord/Base/update_all/class

```ruby
User.update_all(:password, 'xxxxxx')
User.update_all(:latitute, '50 + 0.001 * users.id')
# ... etc
```

2019-01-09 16:47 UTC, roschaefer commented
@dkuku there are very similar rake tasks for dumping and restoring already :astonished: 

![2019-01-09-174651_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/50914302-8d203b00-1436-11e9-8153-bef84ca887a4.png)

2019-01-09 17:00 UTC, roschaefer commented
@dkuku okay :+1: I ran the task on my machine. The `dump` task seems to be a duplicate of the dump task from https://github.com/sgruhier/capistrano-db-tasks. Unfortunately their dump task fails:
```
robert@e480 ~/D/r/backend> bin/rails db:data:dump
rails aborted!
TypeError: no implicit conversion of Pathname into String
/home/robert/.gem/ruby/2.5.1/gems/activerecord-5.1.6/lib/active_record/tasks/postgresql_database_tasks.rb:108:in `system'
/home/robert/.gem/ruby/2.5.1/gems/activerecord-5.1.6/lib/active_record/tasks/postgresql_database_tasks.rb:108:in `run_cmd'
/home/robert/.gem/ruby/2.5.1/gems/chrono_model-0.12.1/lib/active_record/tasks/chronomodel_database_tasks.rb:30:in `data_dump'
/home/robert/.gem/ruby/2.5.1/gems/chrono_model-0.12.1/lib/chrono_model/railtie.rb:31:in `block (2 levels) in <class:Railtie>'
/home/robert/.gem/ruby/2.5.1/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/robert/.gem/ruby/2.5.1/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/robert/.gem/ruby/2.5.1/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/home/robert/.gem/ruby/2.5.1/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:data:dump
(See full trace by running task with --trace)
robert@e480 ~/D/r/backend> ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

Apparently [IFAD's chronomodel](https://github.com/ifad/chronomodel/) does not like the db tasks? :cry: 


@dkuku shall I send you the dump via Slack?

2019-01-09 17:50 UTC, roschaefer commented
@dkuku yes, but all foreign keys would need to be shuffled, too. The correct way to say is "It breaks referential integrity", from [here](https://dba.stackexchange.com/questions/168023/how-to-anonymize-pg-dump-output-before-it-leaves-server).

I think it does not need to be done now.

2019-01-09 17:57 UTC, dkuku commented
@roschaefer you can send it to me via slack.
I'll look at the data shuffling thingy too. I found a gem that might solve this.
https://github.com/sunitparekh/data-anonymization

2019-01-10 11:08 UTC, roschaefer commented on backend/lib/tasks/db.rake
> +        broadcast.creator_id = @user_ids.sample
Hm, I would not do *that* because it gets confusing. E.g. @ciremoussadia is working on a PR where we update the user role if you create a broadcast.

2019-01-10 11:10 UTC, roschaefer commented on backend/lib/tasks/db.rake
> +        broadcast.creator_id = @user_ids.sample
I don't know how to do proper anonymization :laughing: maybe you can do some research if the user `id` *itself* is a means of de-anonymization and if yes, what are the counter-measures?

Maybe it's not necessary after all? :man_shrugging:

2019-01-10 11:13 UTC, roschaefer commented
@dkuku that gem looks OK to me on the first glimpse. Last commit not too old, a couple of stars and focused use case. Does it do sth. to the `id`? It does not seem so, does it?

2019-01-10 11:17 UTC, dkuku commented
when playing with it yesterday I found that we really want to anonymize the
impressions table so it's not possible to recover what have you voted for.
But the foreign key constrains need to be removed temporary and I need to
find where it is stored-probably a join table because I can't update
Impression.first.creator_id even if I can see it in the rails console.

On Thu, 10 Jan 2019, 11:10 Robert Schäfer <notifications@github.com wrote:

> *@roschaefer* commented on this pull request.
> ------------------------------
>
> In backend/lib/tasks/db.rake
> <https://github.com/roschaefer/rundfunk-mitbestimmen/pull/1013#discussion_r246719494>
> :
>
> > @@ -5,16 +5,25 @@ namespace :db do
>
>        puts 'You do not want to anonymize production data'
>
>      else
>
>        puts 'Anonymizing user data'
>
> -
>
> +      @user_ids = User.ids.shuffle
>
> +      Broadcast.find_each do |broadcast|
>
> +        broadcast.creator_id = @user_ids.sample
>
>
> I don't know how to do proper anonymization 😆 maybe you can do some
> research if the user id *itself* is a means of de-anonymization and if
> yes, what are the counter-measures?
>
> Maybe it's not necessary after all? 🤷‍♂️
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/roschaefer/rundfunk-mitbestimmen/pull/1013#discussion_r246719494>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA3L8_xMjCHVBkhp55QMc0XR1-BFl_mSks5vBx-XgaJpZM4ZxNS5>
> .
>

2019-01-10 11:20 UTC, roschaefer commented
@dkuku the foreign key is constraint comes from the database migrations. Ugh, good look to get rid of them. ~Maybe postgres allows to dump the data without foreign key constraints?~ that will not help you because you need to get rid of the constraints earlier

2019-01-16 18:56 UTC, roschaefer commented
@dkuku could you please: `git fetch` and `git merge origin/master`? Given that `origin` is the name of this remote.

2019-01-23 18:38 UTC, roschaefer commented
We could namespace the rake tasks `db:anonymized:dump` no?

2026-09-20 22:05 UTC, closed without merging