[WIP] 390 monthly email list revised
roschaefer/rundfunk-mitbestimmen pull request #727
Opened 2018-07-30 16:07 UTC by mz99

Since the last PR was accidentally merged already, here is the new branch. Should reasons_for_notifications be refactored to be more decoupled (separate each scenario into own methods)?

2018-07-30 19:48 UTC, roschaefer requested changes
Awesome work :1st_place_medal: 

Here are a few suggestions for you. Also consider to try out some of the mail interceptor gems for rails: https://github.com/ryanb/letter_opener
https://mailcatcher.me/

2018-07-30 19:48 UTC, roschaefer commented on backend/app/mailers/user_mailer.rb
> +    mail(to: @user.email, subject: 'New happenings at Rundfunk Mitbestimmen')
You could translate the subject line here.

For authenticated users the language is stored in the user's profile: `user.locale`. If it's set, please translate the subject. If it's not set, assume a German-speaking user.

2018-07-30 19:48 UTC, roschaefer commented on backend/app/models/user.rb
> +    distributed_sum = impressions.to_a.sum { |i| i[:amount].to_f }
Always try to use ActiveRelation whenever possible. So this line here is equivalent to: `impressions.sum(:amount)`.

2018-07-30 19:48 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :no_given_amount_for_supported_broadcasts if impressions.to_a.any? { |r| r[:response] == 'positive' } && distributed_sum.zero?
I would just check for any supported broadcast where the `amount` was not set, yet. With ActiveRelation this would be `impression.positive.where(amount: nil).present?`

2018-07-30 19:48 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
Same, you can do `impressions.where(amount: 17.5)`.

2018-07-30 19:48 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
By the way, in production this here:
```
Impression.where(amount: 17.5)
```
results in
```
=> 139
```
We are in desperate need of your feature!

2018-07-30 19:48 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
Instead of magic numbers, you can also use: `Impression::BUDGET`

2018-07-30 19:48 UTC, roschaefer commented on backend/app/views/user_mailer/monthly_news.html.erb
> +    <p> Here are the new broadcasts at Rundfunk Mitbestimmen since you last logged in:
Yes, great! Can we translate an email template somehow?

2018-07-30 19:48 UTC, roschaefer commented on backend/app/views/user_mailer/monthly_news.html.erb
> +  The Rundfunk Mitbestimmen team </p>
Super cool

2018-07-30 19:48 UTC, roschaefer commented on backend/lib/tasks/monthly_mailer.rake
> +  task monthly_news: :environment do
Yes, great! Can we do this on a regular basis? Maybe with this gem here: https://github.com/javan/whenever

2018-07-30 19:48 UTC, roschaefer commented on backend/spec/models/user_spec.rb
> +        user.update_columns(last_login: Time.current)
Can you add a test case to check if we run into `NilPointerException` if `user.last_login` is `nil`?

2018-07-30 19:48 UTC, roschaefer commented on backend/app/mailers/user_mailer.rb
> +    mail(to: @user.email, subject: 'New happenings at Rundfunk Mitbestimmen')
Check out https://guides.rubyonrails.org/i18n.html
We have a few translations in these folder: https://github.com/roschaefer/rundfunk-mitbestimmen/tree/master/backend/config/locales
You can google translate the German part and ask a native speaker to double-check (e.g. me).

2018-07-31 15:02 UTC, mz99 commented on backend/app/views/user_mailer/monthly_news.html.erb
> +    <p> Here are the new broadcasts at Rundfunk Mitbestimmen since you last logged in:
This might work https://stackoverflow.com/questions/8836859/how-to-translate-email-messages-body-using-the-i18n-gem

2018-08-06 19:28 UTC, mz99 commented on backend/app/mailers/user_mailer.rb
> +    mail(to: @user.email, subject: 'New happenings at Rundfunk Mitbestimmen')
As for translating the subject line, can I simply set the config/application.rb to default to German (config.i18n.default_locale = :de) so that if locale is not set then it defaults to sending the German translation, or find another way?

2018-08-06 20:15 UTC, mz99 commented on backend/app/views/user_mailer/monthly_news.html.erb
> +    <p> Here are the new broadcasts at Rundfunk Mitbestimmen since you last logged in:
The email templates should be using the translation now. One thing that might be wonky is for monthly_new.html.erb, the sign off line doesn't have the line break after the valediction. Can I add the tag <br> inside the translation yml itself to fix it?

2018-08-06 20:48 UTC, roschaefer commented on backend/app/mailers/user_mailer.rb
> +    mail(to: @user.email, subject: 'New happenings at Rundfunk Mitbestimmen')
I think the default is already `de`. You can of course just try it out and in case set a default. Or you can send both versions. The emails send by Auth0 have an English and a German version.

2018-08-06 20:51 UTC, roschaefer commented on backend/app/views/user_mailer/monthly_news.html.erb
> +    <p> Here are the new broadcasts at Rundfunk Mitbestimmen since you last logged in:
You mean writing html inside translation files? That is perfectly possible. We do it a lot in the frontend. E.g. for links. The backend translations should have that, too. I don't know how they work, but I guess you can pass variables etc. and use those inside translations and/or use html.

2018-08-06 20:52 UTC, roschaefer commented on backend/app/views/user_mailer/monthly_news.html.erb
> +    <p> Here are the new broadcasts at Rundfunk Mitbestimmen since you last logged in:
The translation method in rails probably has a method to sign the returned string as html safe.

2018-08-06 20:54 UTC, roschaefer commented on backend/app/views/user_mailer/monthly_news.html.erb
> +    <p> Here are the new broadcasts at Rundfunk Mitbestimmen since you last logged in:
There you go: https://guides.rubyonrails.org/i18n.html#using-safe-html-translations

2018-08-06 20:59 UTC, roschaefer commented on backend/config/locales/de.yml
> +          recently_created_broadcasts: Hier sind die neuen Sendungen, die seit Ihrer letzten Anmeldung den Rundfunk Mitbeständen hinzugefügt wurden:
Throughout the app we're using the informal, not very polite way of addressing "Du" instead of "Sie". The translation is perfect :ok_hand: but very formal. I will fix the translations as soon as this PR is ready for mere

2018-08-06 21:02 UTC, roschaefer commented
Nice work! @Kachulio1 and maybe @aonomike do you want to pair with @mz99 on this PR maybe? Pretty interesting stuff for you, I guess. I can chip tomorrow if you like.

2018-08-20 17:42 UTC, mz99 commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
Not clear what your referring to with Impression::BUDGET, could you give an example?

2018-08-20 18:09 UTC, mz99 commented on backend/lib/tasks/monthly_mailer.rake
> +  task monthly_news: :environment do
Should I start with every month for now?

2018-08-21 11:53 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :no_given_amount_for_supported_broadcasts if impressions.to_a.any? { |r| r[:response] == 'positive' } && distributed_sum.zero?
@mz99 magic :stars: https://api.rubyonrails.org/classes/ActiveRecord/Enum.html

2018-08-21 11:56 UTC, roschaefer commented on backend/lib/tasks/monthly_mailer.rake
> +  task monthly_news: :environment do
Up to you :smile:  I would say, maybe one month or two weeks. Developers make decisions :wink: You can check your email inbox and see which schedule of notifications is the least annoying for you.

2018-08-21 11:59 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
It's here: https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/backend/app/models/impression.rb#L8

By the way, I use `git grep` a lot (or the respective vim plugin `vim-fugitive`). That helps if you code in a dynamically typed language like ruby. So you could e.g. `git grep 'BUDGET'` and see if it's in the repository somewhere.

2018-08-21 12:00 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
There is also a Wikipedia article about [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) and why they should be avoided. We use `Impression::BUDGET` to have the German monthly broadcasting fees at a central location.

2018-08-21 12:06 UTC, roschaefer commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.where(amount: 17.5)
Same same:
```ruby
    reasons << :unbalanced_distribution if impressions.where(amount: Impression::BUDGET)
```
You could also check for smaller amounts, e.g. (amout is greater or equal 0.75 * Impression::BUDGET). See the section of Active Record Query Interface how to implement `>`: https://guides.rubyonrails.org/v3.0.3/active_record_querying.html

2018-08-21 20:09 UTC, mz99 commented on backend/spec/models/user_spec.rb
> +        user.update_columns(last_login: Time.current)
Done

2018-09-05 19:14 UTC, mz99 commented on backend/app/models/user.rb
> +    reasons << :unbalanced_distribution if impressions.to_a.any? { |r| r[:response] == 'positive' && r[:amount] == 17.5 }
Understood. It was simply the BUDGET constant inside the Impression model you were referencing, I had thought it was something else.

2018-09-05 19:51 UTC, mz99 commented on backend/app/models/user.rb
> +    reasons << :no_given_amount_for_supported_broadcasts if impressions.to_a.any? { |r| r[:response] == 'positive' } && distributed_sum.zero?
Very cool, good to know.

2018-09-05 19:58 UTC, mz99 commented on backend/spec/models/user_spec.rb
> +        user.update_columns(last_login: Time.current)
subbed in Impression::BUDGET for the spec line 35 as well

2018-09-05 19:59 UTC, mz99 commented on backend/spec/models/user_spec.rb
> +        user.update_columns(last_login: Time.current)
subbed in Impression::BUDGET for spec line 35 as well

2018-09-18 09:31 UTC, faithngetich commented
@mz99 It looks like the pending migrations are what is making the build fail. You might want to run them and see if the build passes.

2018-09-21 11:07 UTC, roschaefer commented
@faithngetich feel free to fix it yourself. There is no such thing as code ownership, but [collective code ownership](https://martinfowler.com/bliki/CodeOwnership.html). The source branch of this PR is from our origin repository, so you should have write permissions.

2026-09-20 22:05 UTC, closed without merging